### ISSUE TITLE
Use CHAR_BIT instead of writing your own shitty copy of it

### ISSUE THREAD

**Issue by nimaje** [nomemory/bloomfilters-c#1]
If you actually use `CHAR_BIT` that code would have a change to be portable to platforms where chars don't have 8 bits.
Instead you have your own copy of it set to 8, so trying to write portable code without figuring out the right size for `char` making it unportable

**Comment by nomemory** [comment]
Didn't know about `CHAR_BIT` from `limits.h`. Thanks!
